/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as HiringRouteImport } from './routes/hiring'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHiringPartnersRouteImport } from './routes/admin.hiring-partners'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminApplicantsRouteImport } from './routes/admin.applicants'
import { Route as AdminApplicantApplicantIdRouteImport } from './routes/admin.applicant.$applicantId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringRoute = HiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHiringPartnersRoute = AdminHiringPartnersRouteImport.update({
  id: '/admin/hiring-partners',
  path: '/admin/hiring-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicantsRoute = AdminApplicantsRouteImport.update({
  id: '/admin/applicants',
  path: '/admin/applicants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicantApplicantIdRoute =
  AdminApplicantApplicantIdRouteImport.update({
    id: '/admin/applicant/$applicantId',
    path: '/admin/applicant/$applicantId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hiring': typeof HiringRoute
  '/industries': typeof IndustriesRoute
  '/services': typeof ServicesRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/hiring-partners': typeof AdminHiringPartnersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applicant/$applicantId': typeof AdminApplicantApplicantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hiring': typeof HiringRoute
  '/industries': typeof IndustriesRoute
  '/services': typeof ServicesRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/hiring-partners': typeof AdminHiringPartnersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/applicant/$applicantId': typeof AdminApplicantApplicantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/hiring': typeof HiringRoute
  '/industries': typeof IndustriesRoute
  '/services': typeof ServicesRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/hiring-partners': typeof AdminHiringPartnersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/applicant/$applicantId': typeof AdminApplicantApplicantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/hiring'
    | '/industries'
    | '/services'
    | '/admin/applicants'
    | '/admin/enquiries'
    | '/admin/hiring-partners'
    | '/admin/login'
    | '/admin/testimonials'
    | '/jobs/$jobId'
    | '/admin/'
    | '/admin/applicant/$applicantId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/hiring'
    | '/industries'
    | '/services'
    | '/admin/applicants'
    | '/admin/enquiries'
    | '/admin/hiring-partners'
    | '/admin/login'
    | '/admin/testimonials'
    | '/jobs/$jobId'
    | '/admin'
    | '/admin/applicant/$applicantId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/hiring'
    | '/industries'
    | '/services'
    | '/admin/applicants'
    | '/admin/enquiries'
    | '/admin/hiring-partners'
    | '/admin/login'
    | '/admin/testimonials'
    | '/jobs/$jobId'
    | '/admin/'
    | '/admin/applicant/$applicantId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HiringRoute: typeof HiringRoute
  IndustriesRoute: typeof IndustriesRoute
  ServicesRoute: typeof ServicesRoute
  AdminApplicantsRoute: typeof AdminApplicantsRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminHiringPartnersRoute: typeof AdminHiringPartnersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApplicantApplicantIdRoute: typeof AdminApplicantApplicantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring': {
      id: '/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hiring-partners': {
      id: '/admin/hiring-partners'
      path: '/admin/hiring-partners'
      fullPath: '/admin/hiring-partners'
      preLoaderRoute: typeof AdminHiringPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applicants': {
      id: '/admin/applicants'
      path: '/admin/applicants'
      fullPath: '/admin/applicants'
      preLoaderRoute: typeof AdminApplicantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applicant/$applicantId': {
      id: '/admin/applicant/$applicantId'
      path: '/admin/applicant/$applicantId'
      fullPath: '/admin/applicant/$applicantId'
      preLoaderRoute: typeof AdminApplicantApplicantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HiringRoute: HiringRoute,
  IndustriesRoute: IndustriesRoute,
  ServicesRoute: ServicesRoute,
  AdminApplicantsRoute: AdminApplicantsRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminHiringPartnersRoute: AdminHiringPartnersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApplicantApplicantIdRoute: AdminApplicantApplicantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
